---

extends:
  - 'airbnb-base'
  - plugin:import/errors
  - plugin:import/warnings

env:
  node: true

rules:
  no-console: off

parser: babel-eslint

parserOptions:
  ecmaVersion: 2017
  sourceType: module
